CREATE TABLE USER(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
PRIMARY KEY(id)
);


CREATE TABLE POINT(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
iduser SMALLINT UNSIGNED NOT NULL,
latitude DOUBLE, 
longitude DOUBLE,
altitude INT,
date DATETIME,

CONSTRAINT fk_user_point
	FOREIGN KEY (iduser)
	REFERENCES USER(id),
PRIMARY KEY(id)
);

CREATE TABLE LABEL(
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
iduser SMALLINT UNSIGNED NOT NULL,

starttime DATETIME,
endtime DATETIME,
mode VARCHAR(15),

CONSTRAINT fk_user_label
	FOREIGN KEY (iduser)
	REFERENCES USER(id),
PRIMARY KEY(id)
);

